### ISSUE TITLE
可以支持xmind zen吗？

### ISSUE THREAD

**Issue by hauusu** [zhuifengshen/xmind2testcase#10]
请问作者可以支持xmind zen吗，现在解析zen文件时提示‘该文件无法正常打开，请勿修改并保存，否则文件内容将会永久性丢失！’ 和 ‘你可以尝试使用xmin 8 update 3 或更新版本打开。

**Comment by zhuifengshen** [comment]
xmind zen文件是json和xmind8文件是xml，现在大家使用xmind8比较多，后面如果用户量大，再做考虑
