### ISSUE TITLE
禅道导入时没有显示优先级，需要手动再次设置

### ISSUE THREAD

**Issue by vvccool** [zhuifengshen/xmind2testcase#11]

**Comment by zxh66481** [comment]
也许是你的禅道中并不是以“高”，“中”，“低”的形式展示优先级。
如果如我所说， 你可以尝试修改修改zenmdao.py中的gen_case_priority方法

**Comment by zhuifengshen** [comment]
![image](https://user-images.githubusercontent.com/6891304/77143558-8bccb280-6abe-11ea-9bbd-790418c3b8d5.png)

如果你的禅道中没有设置”高中低“优先级，可以设置或者自定义一下代码

**Comment by kingfeng999** [comment]
转化为禅道用例类型和禅道默认用例类型不一样，优先级也不同，我是开源版本的禅道，为此，
大致修改了 zentao.py 文件的优先级和用例类型，如下：

# 定义用例优先级
def gen_case_priority(priority):
    mapping = {1: 1, 2: 2, 3: 3, 4: 4}
    if priority in mapping.keys():
        return mapping[priority]
    else:
        return 2

# 定义用例类型
def gen_case_type(case_type):
    mapping = {1: "功能测试", 2: "接口测试"}
    if case_type in mapping.keys():
        return mapping[case_type]
    else:
        return "功能测试"

是不是除了 zentao.py 这个文件之外，还有别的文件我需要修改呢？请问这个该如何处理？谢谢！
