### ISSUE TITLE
启动web端 报错

### ISSUE THREAD

**Issue by wch352136** [zhuifengshen/xmind2testcase#15]
启动web端的时候 报错，具体截图如下：
![image](https://user-images.githubusercontent.com/17609338/55848122-806aca80-5b7e-11e9-9ff9-1e9205dc9248.png)

**Comment by ysnicelife** [comment]
我也遇到了这个问题

**Comment by Always-test** [comment]
我也遇到了这个问题，是windows系统的问题吗，之前安装的可以启动成功

**Comment by Sniper970119** [comment]
> 
> 
> 我也遇到了这个问题，是windows系统的问题吗，之前安装的可以启动成功

用源码直接运行就好了

**Comment by fengbinTester** [comment]
> 
> 
> > 我也遇到了这个问题，是windows系统的问题吗，之前安装的可以启动成功
> 
> 用源码直接运行就好了

能说一下怎么启动吗

**Comment by zhuifengshen** [comment]
1、Python pip安装可执行的类库后，如果显示command not found，则需要将指定版本的Python bin路径（/usr/local/lib/python3.6.1/bin）添加进PATH中，在用户目录下.bashr或.zshrc文件添加PATH，以MacBook为例：
export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.6/bin
export PATH=$PATH:/usr/local/lib/python3.7.0/bin
如果添加Python2，则：/Library/Frameworks/Python.framework/Versions/2.7/bin
2、windows平台安装时勾选了pip和Add python.exe to Path
