### ISSUE TITLE
为什么xmind导出的cvs每行都会多一行呢？

### ISSUE THREAD

**Issue by caihuan123456** [zhuifengshen/xmind2testcase#17]
![image](https://user-images.githubusercontent.com/44487476/58778160-0269f380-8604-11e9-8c48-a574274888e1.png)

**Comment by caihuan123456** [comment]
问题已解决，楼主不用看了
在打开文件时，手工指定newline参数为""即可避免空行

**Comment by caihuan123456** [comment]
参考源码
def open(file, mode='r', buffering=None, encoding=None, errors=None, newline=None, closefd=True)：

On input, if newline is None, universal newlines mode is
      enabled. Lines in the input can end in '\n', '\r', or '\r\n', and
      these are translated into '\n' before being returned to the
      caller. If it is '', universal newline mode is enabled, but line
      endings are returned to the caller untranslated.

**Comment by fishasen** [comment]
@caihuan123456  在代码里加newline=''，貌似还是不行嘛！
