### ISSUE TITLE
你可以尝试使用 XMind 8 Update 3 或更新版本打开

### ISSUE THREAD

**Issue by never112** [zhuifengshen/xmind2testcase#19]
新的ximind文件无法转换。ximind：zen 产生文件无法转换
You can try using XMind 8 Update 3 or later version to open
你可以尝试使用 XMind 8 Update 3 或更新版本打开

**Comment by liyinchigithub** [comment]
ximind：zen 有这个问题，就办不会

**Comment by zhuifengshen** [comment]
![image](https://user-images.githubusercontent.com/6891304/77143869-5d030c00-6abf-11ea-85e4-fb5c3849b8ef.png)

暂时只支持经典版系列，不支持 XMind Zen
