### ISSUE TITLE
在禅道中，模块下存在子模块， 希望导入时能对应。

### ISSUE THREAD

**Issue by zxh66481** [zhuifengshen/xmind2testcase#22]
产品>模块>子模块>用例
在禅道中，模块维护存在着上下级关系，并不希望是在标题上体现，而是希望能对应到相应的子模块中
，希望作者能在下次更新时考虑该需求。

**Comment by zhuifengshen** [comment]
因为禅道官方不支持导入模块关系，所以只能折衷在标题上”曲线救国“
