### ISSUE TITLE
testlink自定义字段要怎么导入?比如用例编写者、对应开发

### ISSUE THREAD

**Issue by liyinchigithub** [zhuifengshen/xmind2testcase#23]
![image](https://user-images.githubusercontent.com/19643260/69707463-c9cf5080-1134-11ea-9326-354a57de71c5.png)

**Comment by zhuifengshen** [comment]
自定义部分需要自行扩展testlink.py，加入自定义解析

**Comment by liyinchigithub** [comment]
@zhuifengshen  明白了，谢谢
