### ISSUE TITLE
通过 workbook.getData()方法获取的json，label为None

### ISSUE THREAD

**Issue by zxh66481** [zhuifengshen/xmind2testcase#24]
![image](https://user-images.githubusercontent.com/57941254/70688333-848e4f80-1cec-11ea-9fb0-268ea3715ff5.png)

![image](https://user-images.githubusercontent.com/57941254/70688635-2f9f0900-1ced-11ea-8864-6162f9e636c3.png)

请问我的问题可能是出在哪里？

**Comment by zhuifengshen** [comment]
label是标签（上图中的”性能测试“），不是标注
