### ISSUE TITLE
设置了标签自动无效，导出的结果仍然是手动

### ISSUE THREAD

**Issue by aileen20082529** [zhuifengshen/xmind2testcase#3]
设置了标签自动无效，导出的结果仍然是手动

**Comment by bigyaoer** [comment]
metadata.py里面初始化数据时写死了execution_type='1'

**Comment by zxh66481** [comment]
首先你需要看一下禅道中，测试类型字段的选项都有哪一些， 然后修改zandao.py中的gen_case_type方法

**Comment by zhuifengshen** [comment]
Fixed，最新版已修复，欢迎试用
