### ISSUE TITLE
使用xmind导入没有具体转换用例

### ISSUE THREAD

**Issue by ggdkay** [zhuifengshen/xmind2testcase#6]
第一种方法：
workbook = xmind.load(xmind_file)
data = workbook.getData()
执行加载后，显示如下的内容，

第二种方法：
web网页转换一样的错误

操作第三方法：
下载xmind测试用例，选取产品其中一个模块转换也是一样的错误

[{'id': '7abtd0ssc7n4pi1nu6i7b6lsdh', 'title': 'Sheet 1', 'topic': {'id': '1vr0lcte2og4t2sopiogvdmifc', 'link': None, 'title': 'Warning\n警告\nAttention\nWarnung\n경고', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '71h1aip2t1o8vvm0a41nausaar', 'link': None, 'title': 'This file can not be opened normally, please do not modify and save, otherwise the contents will be permanently lost！', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '428akmkh9a0tog6c91qj995qdl', 'link': None, 'title': 'You can try using XMind 8 Update 3 or later version to open', 'note': None, 'label': None, 'comment': None, 'markers': []}]}, {'id': '2kb87f8m38b3hnfhp450c7q35e', 'link': None, 'title': '该文件无法正常打开，请勿修改并保存，否则文件内容将会永久性丢失！', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '3m9hoo4a09n53ofl6fohdun99f', 'link': None, 'title': '你可以尝试使用 XMind 8 Update 3 或更新版本打开', 'note': None, 'label': None, 'comment': None, 'markers': []}]}, {'id': '7r3r4617hvh931ot9obi595r8f', 'link': None, 'title': '該文件無法正常打開，請勿修改並保存，否則文件內容將會永久性丟失！', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '691pgka6gmgpgkacaa0h3f1hjb', 'link': None, 'title': '你可以嘗試使用 XMind 8 Update 3 或更新版本打開', 'note': None, 'label': None, 'comment': None, 'markers': []}]}, {'id': '0f2e3rpkfahg4spg4nda946r0b', 'link': None, 'title': 'この文書は正常に開かないので、修正して保存しないようにしてください。そうでないと、書類の内容が永久に失われます。！', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '4vuubta53ksc1falk46mevge0t', 'link': None, 'title': 'XMind 8 Update 3 や更新版を使って開くこともできます', 'note': None, 'label': None, 'comment': None, 'markers': []}]}, {'id': '70n9i4u3lb89sq9l1m1bs255j5', 'link': None, 'title': 'Datei kann nicht richtig geöffnet werden. Bitte ändern Sie diese Datei nicht und speichern Sie sie, sonst wird die Datei endgültig gelöscht werden.', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '1qpc5ee298p2sqeqbinpca46b7', 'link': None, 'title': 'Bitte versuchen Sie, diese Datei mit XMind 8 Update 3 oder später zu öffnen.', 'note': None, 'label': None, 'comment': None, 'markers': []}]}, {'id': '4dmes10uc19pq7enu8sc4bmvif', 'link': None, 'title': 'Ce fichier ne peut pas ouvert normalement, veuillez le rédiger et sauvegarder, sinon le fichier sera perdu en permanence. ', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '5f0rivgubii2launodiln7sdkt', 'link': None, 'title': "Vous pouvez essayer d'ouvrir avec XMind 8 Update 3 ou avec une version plus récente.", 'note': None, 'label': None, 'comment': None, 'markers': []}]}, {'id': '10pn1os1sgfsnqa8akabom5pej', 'link': None, 'title': '파일을 정상적으로 열 수 없으며, 수정 및 저장하지 마십시오. 그렇지 않으면 파일의 내용이 영구적으로 손실됩니다!', 'note': None, 'label': None, 'comment': None, 'markers': [], 'topics': [{'id': '0l2nr0fq3em22rctapkj46ue58', 'link': None, 'title': 'XMind 8 Update 3 또는 이후 버전을 사용하여', 'note': None, 'label': None, 'comment': None, 'markers': []}]}]}}]

**Comment by zhuifengshen** [comment]
你的xmind软件是不是xmind zen，如果是，请使用xmind8系列
