### ISSUE TITLE
导出结果，内容格式有误

### ISSUE THREAD

**Issue by tester20183450** [zhuifengshen/xmind2testcase#7]
{
        "name": "\u7528\u529b1 \u5b50\u4e3b\u9898 1 \u5b50\u4e3b\u9898 1",
        "version": 1,
        "summary": "\u7528\u529b1 \u5b50\u4e3b\u9898 1 \u5b50\u4e3b\u9898 1",
        "preconditions": "\u65e0",
        "execution_type": 1,
        "importance": 2,
        "estimated_exec_duration": 3,
        "status": 7,
        "result": 0,
        "steps": [],
        "product": "\u4e2d\u5fc3\u4e3b\u9898",
        "suite": "\u5206\u652f\u4e3b\u9898 1"
    }

**Comment by zhuifengshen** [comment]
testcases = get_xmind_testcase_list(xmind_file)
    print('Convert Xmind to testcases dict data:\n%s' %
          json.dumps(testcases, indent=4, separators=(',', ': '), ensure_ascii=False))

包含中文，输出时加上ensure_ascii即可
