### ISSUE TITLE
web端导出cvs文件打开中文乱码

### ISSUE THREAD

**Issue by chongchong01** [zhuifengshen/xmind2testcase#8]

**Comment by Phoenix-Ann** [comment]
码主 [CSV乱码问题](https://blog.csdn.net/tjj3027/article/details/80257007)

楼主 
[excel打开csv 出现乱码怎么解决](https://jingyan.baidu.com/article/380abd0a21cfb61d90192c13.html)
> 以导入数据的方式打开.CSV文件。
>1. 打开Excel并新建一个空白的表，然后点【数据】——>【从文本/CSV】——>然后选择你要导入的.CSV文件——>【导入】
> 2. 然后选择【文件原始格式】中 选择 --无--

**Comment by zhuifengshen** [comment]
导出格式默认就是utf-8，乱码是因为打开csv文件的软件默认不是使用utf-8

**Comment by git564733702** [comment]
以导入数据的方式打开。CSV文件。

打开的Excel并新建一个空白的表，然后点【数据】 - >【从文本/ CSV】 - >然后选择你要导入的CSV文件 - >【导入】
然后选择【文件原始格式】中选择 - UTF-8
![QQ图片20190328213726](https://user-images.githubusercontent.com/48816144/55161995-c2b90280-51a1-11e9-88ef-e7aa11f9bfd7.png)
通过这种方式打开的格式有点乱，怎么办？也设置了逗号作为分隔符了
